config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  resources :picture_tags
  resources :tags, only: [:index, :new, :create, :show]
  resources :comments, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit]
  resources :pictures, only: [:index, :new, :create, :show, :destroy]
  resources :sessions

  get '/signup', to: 'users#signup'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#logout'
  root 'sessions#login'
  



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  validates :content, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
    has_many :comments
    has_many :users, through: :comments
    has_many :picture_tags
    has_many :tags, through: :picture_tags
    belongs_to :owner, class_name: "User"

end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :picture_tags
    has_many :pictures, through: :picture_tags

 

    

end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments
    has_many :pictures, through: :comments
    has_many :owned_pictures, class_name: "Picture", foreign_key: "owner_id"
    validates_presence_of :username
    validates_uniqueness_of :username
    validates :email, presence: true
    validates :email, uniqueness: true
    has_secure_password
    accepts_nested_attributes_for :pictures


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # helper_method :current_user, :logged_in?
    before_action :fetch_user
    

    def fetch_user
        @logged_in = logged_in?
        if @logged_in
            @user = User.find(session[:user_id])
        else
            #  redirect_to login_path
        end
    end


    def logged_in?
        !!session[:user_id]
    end

    def log_out_user!
        session.delete(:user_id)
    end 
end

  

    

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @comment = Comment.new
    end
    
    def create
        @comment = Comment.new(comment_params)
        @comment.user_id = session[:user_id]
        @comment.picture_id = session[:picture_id]
        @comment.save
         redirect_to picture_path(session[:user_id])
    end

    def destroy
        @comment = Comment.find(params[:id])
        @picture = @comment.picture
        @comment.destroy
        redirect_to picture_path(@picture)
      end

private

    def comment_params
    params.require(:comment).permit(:user_id, :picture_id, :content)
    end
end

app/controllers/picture_tags_controller.rb
class PictureTagsController < ApplicationController
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

    def index 
        @pictures = Picture.all 
    end

    def new
        @picture = Picture.new
        @comment = Comment.new
        @tag = Tag.new
        @user = current_user
      end
   
    def create 
         @picture = Picture.new(picture_params) 
         if params[:picture][:tags][:name] != ""
            @tag = Tag.create_or_find_by(name: params[:picture][:tags][:name])
            @picture.tags << @tag 
         end
         @picture.owner_id = session[:user_id]
         @picture.save
         if @picture.valid?
            session[:picture_id] = @picture.id
            redirect_to @user
         else
            redirect_to new_picture_path
         end
    end


    def show 
        @picture = Picture.find(params[:id])
        session[:picture_id] = params[:id]
        @comments = @picture.comments
        @comment = Comment.new
    end

    def destroy
        @picture.destroy
        redirect_to pictures_path
    end
   

    private

    def picture_params
        params.require(:picture).permit(:image_url, :title, :owner_id)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :fetch_user, only:[:new, :create]
  

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username:params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to signup_path
  end
end

def destroy
  log_out_user!
  redirect_to new_login_path
end 

  # def destroy
  # @user = User.find_by(username: params[:id]).destroy
  # session[:user_id] = nil
  # redirect_to "/signup"
  # end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all 
    end

    def show
        @tag = Tag.find(params[:id])
        session[:tag_id] = params[:id]
        # @pictures = Picture.all
        @pictures = Picture.new
    end

    def new
       @tag = Tag.new
      end


    def create
        @tag = Tag.create
    end
    
private

    def tag_params
    params.require(:picture).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :fetch_user, only:[:new, :create]

    def index
        @users = User.all 
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else
            redirect_to "/signup"
        end
    end


        def show
            @user = User.find(params[:id])
            @pictures = @user.pictures
            @comments = @user.comments
        end

        def edit
            @user = User.find(params[:id])
        end

    

        # def destroy
        #     User.find_by(username: params[:id]).destroy
        #     session[:user_id] = nil
        #     redirect_to users_path
        # end



    private 

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/picture_tags_helper.rb
module PictureTagsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PictureGram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <%= link_to "Log In", login_path %></h1><div>
  <%= link_to "Sign Up", signup_path %><div>
  <%= link_to "Log Out", logout_path %> <div>

    <%= yield %>
  </body>
</html>

app/views/pictures/index.html.erb
<% @pictures.each do |picture| %>
    <img src=<%= picture.image_url %> width="800" height="600">
    <%end%>

app/views/pictures/show.html.erb
<h4><%= @picture.title %></h4>
<img src=<%=@picture.image_url%> width="800" height="600">
<%= button_to "Delete Photo", @picture, :method => :destroy%> 


<div>
<% @picture.picture_tags.each do |p| %>
   <h6> <%= p.tag.name  %> </h6>
    <%end%>
    <div>

<% @comments.each do |comment| %>
    <h6> <%= comment.content %></h6>
    <%end%>
   <div>

   
  
    <%= form_for @comment do |f| %>
        <%= f.label :comment %>
        <%= f.text_field :content%>  
         <%= f.submit %>
         <%end%>


   

app/views/tags/index.html.erb
<% @tags.each do |tag| %>
<br>
<br>
<br>

    <div>
   <h3> <%= link_to tag.name  %></h3>
    <%end%>
    </div>
   
    

app/views/tags/show.html.erb
<h3><%= @tag.name %></h3>
<div>

<% @tag.pictures.each do |picture| %>
    <img src=<%= picture.image_url %> width="800" height="600">
    <% end %>
  

app/views/users/show.html.erb
<h3><%= @user.username %>'s photos</h3>
<% @pictures.each do |picture| %>
    <img src=<%= picture.image_url %> width="800" height="600">
<% end %>


  
    <%= form_for Picture.new do |pic| %>
    <%= pic.label :image_url %>
    <%= pic.text_field :image_url %>
    <%= pic.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
    <%= pic.label "tag" %>
    <%= pic.fields_for(:tags, Tag.new) do |t| %>
        <%= t.text_field :name %>

    <%end%>
    <%= pic.submit %>
    <%end%> 

  

app/views/users/signup.html.erb
<h1>Signup Form</h1>

<%= form_for User.create do |f| %>
   
    <%= f.label "Username" %>
    <%= f.text_field :username %>
   
    <%= f.label "Email" %>
    <%= f.text_field :email %>
    <%= f.label "Password " %>
    <%= f.password_field :password %>
   
    <%= f.submit %>
    <%end%>
   

    
   

   